version: '3'
services:
  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: redis
  api:
    depends_on: 
      - postgres
      - redis
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      # leave this folder as it is
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres_password
      - PG_DB=postgres
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      # leave this folder as it is 
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'
